version: '3.2'
services:
  go-ipfs:
    build: ./docker/go-ipfs
    ports:
     - "4001:4001"
     - "5001:5001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/"]
      interval: 30s
      timeout: 30s
      retries: 5
    volumes:
      - /data/ipfs:/data/ipfs
  redis:
    build: ./docker/redis
    ports:
      - "127.0.0.1:6379:6379"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6379/"]
      interval: 30s
      timeout: 30s
      retries: 5
    volumes:
      - /data/redis:/data/redis
  pinner:
    depends_on: 
      - go-ipfs
      - redis
    build: .
